version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go"]
    env_file:
      - .env
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db